### PR TITLE
fix: Fixed usage of yaml.safe_load in migration

### PR DESCRIPTION
**Pull request by kewne**
This fixes the migration introduced in #806 

I think the bug was missed in tests because `EDXAPP_FEATURES` is never used, so the code path in question is never exercised...

# Testing

1. Apply all previous migrations `./manage.py migrate instance 0140`;
2. Create an `OpenEdXInstance` with `configuration_extra_settings = 'EDXAPP_FEATURES: { TEST_FLAG: true }'`;
Alternatively, use any environment that contains instances where `configuration_extra_settings` contains `EDXAPP_FEATURES`;
3. Apply migration: `./manage.py migrate instance`;
4. Verify that:
    * before the fix it fails with `AttributeError: module 'yaml' has no attribute 'yaml'`
    * after the fix it succeeds

Related tickets:
* [BB-4230](https://tasks.opencraft.com/browse/BB-4230)

### CODE REVIEW

**Comment by Kelketek** [comment]
:+1:

- ~~[ ] I tested this: (describe what you tested)~~
- [X] I read through the code
- ~~[ ] I checked for accessibility issues~~
- ~~[ ] Includes documentation~~
- ~~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Review by Kelketek — DISMISSED** [review]
:+1:

These code changes make sense, but be sure to verify it's working as expected on stage. This one's a bit tricky to test locally and it's clear that these migrations didn't run in their current form before.

- ~~[ ] I tested this: (describe what you tested)~~
- [X] I read through the code
- ~~[ ] I checked for accessibility issues~~
- ~~[ ] Includes documentation~~
- ~~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Review by nizarmah — APPROVED** [review]
👍🏼 

The change seems to be pretty straight forward to me, to be honest. There's no `yaml.yaml` after all.

I was hoping to test this locally on my vagrant box by destroying the old one and creating a new one, but I had some trouble.

---

I do have a small comment before merging, or after. Can you please add a pull request description that is aligned with the [handbook's expectations](https://handbook.opencraft.com/en/latest/processes/#what-to-include-in-a-pull-request)? Please make sure to include the ticket so I know where to log my time.

**Review by nizarmah — COMMENTED** [review]
Actually, one minute. It just occurred to me that I can test run the migration on stage.

**Review by nizarmah — APPROVED** [review]
When attempting to revert the migration on Stage, without this fix, I get the following error:
```
(opencraft) www-data@stage:~/opencraft$ honcho run ./manage.py migrate instance 0140_update_openstack_base_image_20210315_1545
Operations to perform:
  Target specific migration: 0140_update_openstack_base_image_20210315_1545, from instance
Running migrations:
  Rendering model states... DONE
  Unapplying instance.0141_features_to_features_extras...Traceback (most recent call last):
  File "./manage.py", line 37, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/db/migrations/executor.py", line 269, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/db/migrations/migration.py", line 175, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/var/www/.pyenv/versions/opencraft/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 196, in database_backwards
    self.reverse_code(from_state.apps, schema_editor)
  File "/var/www/opencraft/instance/migrations/0141_features_to_features_extras.py", line 35, in backward
    if config.configuration_extra_settings
AttributeError: module 'yaml' has no attribute 'yaml'
```

Once this fix is applied, I managed to revert and re-apply the migration:
```
(opencraft) www-data@stage:~/opencraft$ honcho run ./manage.py migrate instance 0140_update_openstack_base_image_20210315_1545
Operations to perform:
  Target specific migration: 0140_update_openstack_base_image_20210315_1545, from instance
Running migrations:
  Rendering model states... DONE
  Unapplying instance.0141_features_to_features_extras... OK
(opencraft) www-data@stage:~/opencraft$ honcho run ./manage.py migrate instance 0141_features_to_features_extras
Operations to perform:
  Target specific migration: 0141_features_to_features_extras, from instance
Running migrations:
  Applying instance.0141_features_to_features_extras... OK
```

Approved 👍🏼

**Comment by kewne** [comment]
@nizarmah Thanks: I've added the information you requested.
